### ISSUE TITLE
CA Error

### ISSUE THREAD

**Issue by N0odlez** [napalm-automation-community/napalm-arubaos-switch#24]
When clicking to retrieve information from the switch, I am presented with the following error.
Error connecting to the device at 10.100.100.33: Could not find a suitable TLS CA certificate bundle, invalid path: False

This does not happen if I use the provided test python script which returns the full config as expected.

Any help would be appreciated

## Specifications

  - Netbox Version: 3.6.1
  - NAPALM Version: 4.1.0
  - ArubaOS Plugin Version: 0.2.0
  - Platform: AOS WC.16.10.0009

**Comment by alagoutte** [comment]
What do you have set for ssl_verify ?
